# Generated by Django 3.0 on 2020-11-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('company', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
